server {
    listen 9001;
    server_name localhost;
    root /usr/share/nginx/html;

    location /extra/analysis/ {
        try_files $uri $uri/ /extra/analysis/index.html;
    }

    location = /extra/analysis {
        return 301 /extra/analysis/;
    }
}
