server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location /extra/analyses/ {
        try_files $uri $uri/ /extra/analyses/index.html;
    }

    location = /extra/analyses {
        return 301 /extra/analyses/;
    }
}
